### ISSUE TITLE
Add support for GADLoader

### ISSUE THREAD

**Issue by kmchargue** [media-net/mnet-dfp-hb-sdk#1]
DFP header bidding currently requires either a DFPBannerView or a DFPInterstitial object. In order to use some features, the Google Ad SDK requires loading ads through GADAdLoader objects instead.

To allow support for both in our apps, we need the ability to add bids to a GADAdLoader object as well as banners and interstitials.

**Comment by aniketawati** [comment]
Feature added in release 1.1.1 
[Documentation](http://hb.docs.msas.media.net/integration-of-media-net-header-bidder-for-dfp-ios/) is updated.
